name: build module artifacts for multiple targets

on:
  push:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: "OpenWrt version"
        type: string
        required: true
        default: "23.05.3"

jobs:
  generate-target-matrix:
    runs-on: ubuntu-22.04
    outputs:
      build-matrix: ${{ steps.generate-target-matrix.outputs.build-matrix }}
    env:
      OPENWRT_RELEASE: ${{ inputs.openwrt_version || vars.DEFAULT_OPENWRT_VERSION }}
    steps:
      - name: checkout amneziawg-openwrt
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: prepare virtualenv
        id: prepare-virtualenv
        run: |
          make show-env
          make venv

      - name: generate target matrix
        id: generate-target-matrix
        run: |
          make generate-target-matrix

  build:
    name: "v${{ matrix.build_env.tag }} - ${{ matrix.build_env.pkgarch }} :: ${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }} amneziawg build"
    runs-on: ubuntu-22.04
    needs: generate-target-matrix
    strategy:
      matrix:
        build_env: ${{ fromJson(needs.generate-target-matrix.outputs.build-matrix) }}

    env:
      OPENWRT_RELEASE: ${{ matrix.build_env.tag }}
      OPENWRT_ARCH: ${{ matrix.build_env.pkgarch }}
      OPENWRT_TARGET: ${{ matrix.build_env.target }}
      OPENWRT_SUBTARGET: ${{ matrix.build_env.subtarget }}
      OPENWRT_VERMAGIC: ${{ matrix.build_env.vermagic }}

    steps:
      - name: checkout amneziawg-openwrt
        uses: actions/checkout@v4
        with:
          path: amneziawg-openwrt
          fetch-depth: 0

      - name: checkout openwrt
        uses: actions/checkout@v4
        with:
          path: openwrt
          repository: openwrt/openwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: checkout usign
        uses: actions/checkout@v4
        with:
          path: usign
          repository: openwrt/usign
          fetch-depth: 0

      - name: build usign
        id: build-usign
        run: |
          set -x
          cd usign
          mkdir build
          cd build
          cmake ..
          make -j
          echo "$(pwd)" >> $GITHUB_PATH

      - name: restore cached tools and kernel
        id: cache-tools-kernel-restore
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          key: ${{ runner.os }}-openwrt-cache-toolchain-kernel-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch }}-${{ matrix.build_env.target }}-${{ matrix.build_env.subtarget }}
          restore-keys: |
            ${{ runner.os }}-openwrt-cache-tools-kernel-${{ matrix.build_env.pkgarch }}-
          path: |
            openwrt/.config
            openwrt/.config.old
            openwrt/feeds.conf
            openwrt/bin/**
            openwrt/build_dir/**
            openwrt/dl/**
            openwrt/feeds/**
            openwrt/package/**
            openwrt/staging_dir/**
            openwrt/tmp/**

      - name: build amneziawg
        id: build-amneziawg
        run: |
          set -x
          cd amneziawg-openwrt
          make show-env
          make export-env >> $GITHUB_OUTPUT
          time -p make build-amneziawg
          make prepare-artifacts

      - name: create feed
        id: create-feed
        run: |
          set -x
          cd amneziawg-openwrt
          usign -G -s test.sec -p test.pub
          FEED_SEC_KEY=$(pwd)/test.sec make create-feed
          FEED_PUB_KEY=$(pwd)/test.pub make verify-feed

      - name: upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: amneziawg-${{ steps.build-amneziawg.outputs.version_str }}_v${{ matrix.build_env.tag }}_${{ matrix.build_env.pkgarch}}_${{ matrix.build_env.target}}_${{ matrix.build_env.subtarget}}
          path: awgrelease/*
